### ISSUE TITLE
Any video review about this? Or screenshot? 

### ISSUE THREAD

**Issue by wahyuridiansyah** [aospify/aospify#1]
Any video review about this? Or screenshot?

**Comment by kdrag0n** [comment]
> Any video review about this? Or screenshot?

No, this is an abandoned project that is not guaranteed to work in any way, shape, or form. Expect your device to fail catastrophically; we (the creators) are not to blame for any issues that may arise as a result of using AOSPify.

That being said, I do use this on my secondary device. Here's a screenshot of AOSPify's customized Device menu in Settings (black theme not included):
![image](https://user-images.githubusercontent.com/7930239/52324888-e2992a80-2997-11e9-8460-adfd5a4272b5.png)
